
server:  port: 8201
 
spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://cd-cdb-58vghzre.sql.tencentcdb.com:6288/neusoft_hotel_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.neusoft.hotel.manage.model,com.neusoft.hotel.admin.model
 
#showSql
logging:
  level:
     com.neusoft.hotel: debug
    
 
