
server:  port: 8201
 
spring:
  datasource:
    username: root
    password: sl488234
    url: jdbc:mysql://101.37.19.14:3306/neusoft_hotel_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.neusoft.hotel.manage.model,com.neusoft.hotel.admin.model, com.neusoft.hotel.info.model
 
#showSql
logging:
  level:
     com.neusoft.hotel: debug
    
 
